[package]
name = "factorio_mod_manager"
version = "0.1.0"
authors = ["raiguard <caleb.heuer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
pico-args = "0.4.0"

[[bin]]
name = "fmm"
path = "src/main.rs"
