[package]
name = "factorio_mod_manager"
version = "0.1.0"
authors = ["raiguard <caleb.heuer@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.12.4"
pico-args = "0.4.0"
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.64"

[[bin]]
name = "fmm"
path = "src/main.rs"
