[package]
name = "factorio_mod_manager"
version = "0.1.0"
authors = ["raiguard <caleb.heuer@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.12.4"
lazy_static = "1.4.0"
pico-args = "0.4.0"
regex = "1.4.5"
semver = {version = "0.11.0", features = ["serde"]}
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.64"
zip = "0.5.11"

[[bin]]
name = "fmm"
path = "src/main.rs"
