# The path to the Factorio installation you wish to use
# May be overridden with the `--game-dir` flag
game_dir = "/home/rai/games/factorio"
# The path to the Factorio mods directory
# If `game_dir` is specified and the mods folder is within it, you do not need to add this
# May be overridden with the `--mods-dir` flag
mods_dir = "/home/rai/.factorio/mods/"
# If enabled, `fmm sync-file` will enable or download the latest version of each mod instead of the version in the save file
# Default: false
sync_latest_versions = false
# Your OAUTH token for mod portal access
# This is currently only used for mod uploading, but will eventually replace the `portal` section
# You may alternatively specify your token with the FMM_TOKEN environment variable
# May be overridden with the `--token` flag
token = "12345"

# Mod portal credentials
# These will be automatically retrieved from `player-data.json` in `game_dir'
# Retrieve or reset your token: https://factorio.com -> Profile -> Token
[portal]
token = "12345"
username = "raiguard"

# Customizable mod sets
# Each key will be available for use in the `enable-set` or `sync-set` subcommand
# Dependencies will automatically be enabled
# Specific versions may be specified by appending `@version` to the mod name
[sets]
EditorExtensions = ["EditorExtensions", "Sandbox"]
Krastorio2Beta = ["Krastorio2@1.2.0", "EditorExtensions", "Sandbox"]
